parameters:
#    dan_main.example.class: Dan\MainBundle\Example

services:
#    dan_main.example:
#        class: %dan_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dan_desire_subscriber:
        class: Dan\MainBundle\Subscriber\DesireEventSubscriber
        calls:
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
        tags:
            - { name: jms_serializer.event_subscriber, event: preDeserialize, direction: deserialization, format: json }
            - { name: jms_serializer.event_subscriber, event: postDeserialize, direction: deserialization, format: json }