parameters:
#    dan_user.example.class: Dan\UserBundle\Example

services:
    fos_google.user_provider:
        class: Dan\UserBundle\Security\GoogleProvider
        arguments:
            google: @fos_google.api
            userManager: @fos_user.user_manager
            validator: @validator
            em: @doctrine.orm.entity_manager
            kernel: @kernel
            
    user.factory:
        class: Dan\UserBundle\Service\User
        arguments: [@security.context]
        
    user:
        class: Dan\UserBundle\Entity\User
        factory_service: user.factory
        factory_method: get
