parameters:
#    dan_user.example.class: Dan\UserBundle\Example

services:
    fos_google.user_provider:
        class: Dan\UserBundle\Security\GoogleProvider
        arguments:
            google: @fos_google.api
            userManager: @fos_user.user_manager
            validator: @validator
            em: @doctrine.orm.entity_manager
            kernel: @kernel