parameters:
#    dan_user.example.class: Dan\UserBundle\Example
    oauth.user_provider.class: Dan\UserBundle\Security\FOSUBUserProvider
 
services:
    oauth.user_provider:
        class: "%oauth.user_provider.class%"
        arguments: 
            - @fos_user.user_manager
            - {google: googleId}
        calls:
            - [setKernel,[@kernel]]

#    fos_google.user_provider:
#        class: Dan\UserBundle\Security\GoogleProvider
#        arguments:
#            google: @fos_google.api
#            userManager: @fos_user.user_manager
#            validator: @validator
#            em: @doctrine.orm.entity_manager
#            kernel: @kernel
            
    user.factory:
        class: Dan\UserBundle\Service\User
        arguments: [@security.context]
        
    user:
        class: Dan\UserBundle\Entity\User
        factory_service: user.factory
        factory_method: get


    dan_user.registration.form.type:
        class: Dan\UserBundle\Form\Type\RegistrationFormType
        arguments: [Dan\UserBundle\Entity\User]
        calls:
            - [ setUserManager, [ @fos_user.user_manager ]]
        tags:
            - { name: form.type, alias: dan_user_registration }

    dan_user.resetting.form.type:
        class: Dan\UserBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: dan_user_resetting }
